name: ZweiBooks
version: 2.0
author: Zweisicht
website: http://zweisicht.at

main: me.zweisicht.zweibooks.ZweiBooks

commands: 
  banbook:
    description:  Zeigt euch alle Gebannten Spieler an.
    usage:  /<command>
  book:
    description: Erstellt euch ein beschriebenes Buch.
    usage:  /<command>
  rulesbook:
    description: Erstellt das Regelbuch.
    usage:  /<command>
  booklist:
    description: Zeigt die Liste der Buecher an.
    usage:  /<command>