name: ZweiBooks
version: 2.0
author: Zweisicht
website: http://zweisicht.at

main: me.zweisicht.zweibooks.ZweiBooks

commands: 
  banbook:
    description:  Zeigt euch alle Gebannten Spieler an.
    usage:  /<command>
  book:
    description: Ein beschriebenes Buch.
    usage:  /<command> [Spieler] [Buch]
  rulesbook:
    description: Das Regelbuch.
    usage:  /<command>
  booklist:
    description: Zeigt die Liste der Buecher an.
    usage:  /<command>
  copybook:
    description: Das Buch in der Hand wird gespeichert.
    usage:  /<command>
  editbook:
    description: Editiert das Buch.
    usage:  /<command> [Buch]
  givebook:
    description: Gibt einen Spieler ein Buch.
    usage:  /<command>